### PR TITLE
Fixed Triangle Wave and Implemented Sawtooth

### PR DESCRIPTION
**Pull request by nick5435**
Fixed Triangle Wave and Implemented Sawtooth

### CODE REVIEW

**Comment by nick5435** [comment]
@richard92m

**Comment by nick5435** [comment]
Ignore this.

**Comment by richard92m** [comment]
Verified that it works. Can you merge w/ master before creating the pull request?

**Comment by nick5435** [comment]
I am Git noob. It was made complicated because you were pushing changes as
I was and then merges and BLAH

**Comment by richard92m** [comment]
Same here, man. It looks like you went about branching correctly, just gotta merge w/ master and fix conflicts before sending the pull request.

**Pull request closed without merging**
